import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { decodeJobOptions } from '../../core/repositories/job-options.repository';
import { JobSeeker } from './job-seeker';
import { LanguageService } from '../../core/i18n/language.service';
import data from '../../../../public/data/job-options.json';

describe('Job education dropdowns', () => {
  it('preserves previous country answers and selects a localized country', () => {
    TestBed.configureTestingModule({ providers: [provideHttpClient(), provideHttpClientTesting()] });
    const fixture = TestBed.createComponent(JobSeeker);
    const page = fixture.componentInstance;
    TestBed.inject(HttpTestingController).expectOne('data/job-options.json').flush(data);
    page.form.controls.countries.setValue('Canada, Germany');
    page.go(2);
    fixture.detectChanges();
    const root = fixture.nativeElement as HTMLElement;
    const select = root.querySelector<HTMLSelectElement>('#job-countries')!;
    expect(select.value).toBe('__other');
    expect(root.querySelector<HTMLInputElement>('#job-custom-countries')?.value).toBe('Canada, Germany');
    select.value = 'Germany'; select.dispatchEvent(new Event('change'));
    TestBed.inject(LanguageService).setLanguage('bn'); fixture.detectChanges();
    expect(select.selectedOptions[0].textContent?.trim()).toBe(data.countries.find(c => c.en === 'Germany')!.bn);
    expect(page.form.controls.countries.value).toBe('Germany');
    select.value = ''; select.dispatchEvent(new Event('change'));
    expect(page.form.controls.countries.valid).toBe(true);
    page.reset();
    TestBed.inject(HttpTestingController).verify();
  });
  it('selects experience in years while preserving exact months and role validation', () => {
    TestBed.configureTestingModule({ providers: [provideHttpClient(), provideHttpClientTesting()] });
    const fixture = TestBed.createComponent(JobSeeker);
    const page = fixture.componentInstance;
    TestBed.inject(HttpTestingController).expectOne('data/job-options.json').flush(data);
    page.form.patchValue({ education: 'Diploma', experienceMonths: '18' });
    page.go(1);
    fixture.detectChanges();
    const root = fixture.nativeElement as HTMLElement;
    const select = root.querySelector<HTMLSelectElement>('#job-experienceMonths')!;
    expect(select.value).toBe('__other');
    expect(root.querySelector<HTMLInputElement>('#job-experience-exact')?.value).toBe('18');
    select.value = '24'; select.dispatchEvent(new Event('change')); fixture.detectChanges();
    expect(page.form.controls.experienceMonths.value).toBe('24');
    expect(select.selectedOptions[0].textContent?.trim()).toBe('2 years');
    expect(page.form.controls.experienceRoles.hasError('required')).toBe(true);
    select.value = '0'; select.dispatchEvent(new Event('change')); fixture.detectChanges();
    expect(page.form.controls.experienceRoles.hasError('required')).toBe(false);
    select.value = ''; select.dispatchEvent(new Event('change'));
    expect(page.form.controls.experienceMonths.value).toBe('');
    page.reset();
    TestBed.inject(HttpTestingController).verify();
  });
  it('validates the reference options and rejects duplicates and missing translations', () => {
    expect(decodeJobOptions(data).education).toHaveLength(9);
    expect(decodeJobOptions(data).fieldOfStudy).toHaveLength(13);
    expect(() => decodeJobOptions({ ...data, education: [data.education[0], data.education[0]] })).toThrow();
    expect(() => decodeJobOptions({ ...data, education: [{ id: 'test', en: 'Test' }] })).toThrow();
  });
  it('loads dropdowns, preserves custom answers and switches labels without changing answers', () => {
    TestBed.configureTestingModule({ providers: [provideHttpClient(), provideHttpClientTesting()] });
    const fixture = TestBed.createComponent(JobSeeker);
    const http = TestBed.inject(HttpTestingController);
    fixture.componentInstance.form.controls.education.setValue('Custom certificate');
    http.expectOne('data/job-options.json').flush(data);
    fixture.detectChanges();
    const root = fixture.nativeElement as HTMLElement;
    const degree = root.querySelector<HTMLSelectElement>('#job-education')!;
    expect(degree.value).toBe('__other');
    expect(root.querySelector<HTMLInputElement>('#job-custom-education')?.value).toBe('Custom certificate');
    degree.value = 'Diploma'; degree.dispatchEvent(new Event('change'));
    fixture.detectChanges();
    expect(fixture.componentInstance.form.controls.education.value).toBe('Diploma');
    expect(root.querySelector('#job-custom-education')).toBeNull();
    TestBed.inject(LanguageService).setLanguage('bn'); fixture.detectChanges();
    expect(degree.selectedOptions[0].textContent?.trim()).toBe('ডিপ্লোমা');
    expect(fixture.componentInstance.form.controls.education.value).toBe('Diploma');
    fixture.componentInstance.reset(); fixture.detectChanges();
    expect(degree.value).toBe('');
    http.verify();
  });
});
