export const jobText = {
  resultsTitle: ['Assessment result', 'মূল্যায়নের ফলাফল'],
  resultsIntro: ['Based on your selected country of interest, explore guidance on finding jobs and starting a work-visa application. You can select another country below. These guides do not assess your eligibility or show live vacancies.', 'আপনার পছন্দের দেশের ভিত্তিতে চাকরি খোঁজা ও কর্মভিসার আবেদন শুরুর নির্দেশনা দেখুন। নিচে অন্য দেশ বাছতে পারেন। এই নির্দেশিকা আপনার যোগ্যতা যাচাই করে না বা সরাসরি চাকরির বিজ্ঞপ্তি দেখায় না।'],
  experienceYears: ['Total work experience (years)', 'মোট কাজের অভিজ্ঞতা (বছর)'],
  noExperience: ['No work experience', 'কাজের অভিজ্ঞতা নেই'],
  year: ['year', 'বছর'],
  years: ['years', 'বছর'],
  exactExperience: ['Other — enter exact months', 'অন্য — সঠিক মাসের সংখ্যা লিখুন'],
  optionsLoading: ['Loading options…', 'বিকল্প লোড হচ্ছে…'],
  optionsError: [
    'Options could not be loaded. Try again or choose Other to enter your answer.',
    'বিকল্প লোড হয়নি। আবার চেষ্টা করুন অথবা অন্য বিকল্প বেছে নিজের উত্তর লিখুন।',
  ],
  chooseOption: ['Choose an option', 'একটি বিকল্প বাছুন'],
  otherOption: ['Other — enter your answer', 'অন্য — নিজের উত্তর লিখুন'],
  customAnswer: ['Your answer', 'আপনার উত্তর'],
  summaryTitle: ['Your job-seeker profile', 'আপনার চাকরিপ্রার্থী প্রোফাইল'],
  selfReported: [
    'This summary reflects only the answers you supplied. Qualifications, skills, and language ability have not been verified.',
    'এই সারাংশে শুধু আপনার দেওয়া উত্তর রয়েছে। যোগ্যতা, দক্ষতা বা ভাষাজ্ঞান যাচাই করা হয়নি।',
  ],
  missingTitle: ['Information not provided', 'যেসব তথ্য দেওয়া হয়নি'],
  missingHint: [
    'You can add these details when you know them. Optional information can stay blank; missing answers do not mean you are ineligible for a job or visa.',
    'জানা হলে এই তথ্যগুলো যোগ করতে পারেন। ঐচ্ছিক তথ্য ফাঁকা থাকতে পারে; উত্তর না দেওয়া মানে চাকরি বা ভিসার অযোগ্য হওয়া নয়।',
  ],
  noMissing: [
    'No unanswered profile fields are listed. This does not establish job readiness or employment or visa eligibility.',
    'প্রোফাইলের কোনো অনুত্তরিত ঘর তালিকায় নেই। এটি কাজের প্রস্তুতি, চাকরি বা ভিসার যোগ্যতা নিশ্চিত করে না।',
  ],
  noExperienceRoles: [
    'Not applicable — no work experience reported',
    'প্রযোজ্য নয় — কাজের অভিজ্ঞতা নেই বলে জানিয়েছেন',
  ],
  addInformation: ['Add information', 'তথ্য যোগ করুন'],
  summaryEditHint: [
    'Editing reopens an unfinished draft. Finish the questionnaire again to update this summary.',
    'সম্পাদনা করলে অসমাপ্ত খসড়া আবার চালু হবে। সারাংশ হালনাগাদ করতে প্রশ্নমালা আবার সম্পন্ন করুন।',
  ],
  intro: [
    'Describe your background and preferences for working abroad. Review and edit your answers before finishing.',
    'বিদেশে কাজের জন্য আপনার পটভূমি ও পছন্দ জানান। শেষ করার আগে উত্তরগুলো পর্যালোচনা ও সম্পাদনা করুন।',
  ],
  privacy: [
    'Do not enter names, contact details, passport numbers, employer details, salary, or documents. An unfinished draft stays in this tab for up to 24 hours after your last activity.',
    'নাম, যোগাযোগের তথ্য, পাসপোর্ট নম্বর, নিয়োগকর্তার তথ্য, বেতন বা নথি দেবেন না। সর্বশেষ ব্যবহারের পর সর্বোচ্চ ২৪ ঘণ্টা এই ট্যাবে অসমাপ্ত খসড়া থাকবে।',
  ],
  notice: [
    'These answers are self-reported planning information. This questionnaire does not find jobs, assess work-visa eligibility, or submit applications. Employment and visas are not guaranteed.',
    'এই উত্তরগুলো আপনার দেওয়া পরিকল্পনার তথ্য। এই প্রশ্নমালা চাকরি খোঁজে না, কর্মভিসার যোগ্যতা যাচাই করে না বা আবেদন পাঠায় না। চাকরি বা ভিসার নিশ্চয়তা দেওয়া হয় না।',
  ],
  educationStep: ['Education and skills', 'শিক্ষা ও দক্ষতা'],
  experienceStep: ['Experience and languages', 'অভিজ্ঞতা ও ভাষা'],
  preferencesStep: ['Work preferences', 'কাজের পছন্দ'],
  review: ['Review your answers', 'উত্তরগুলো পর্যালোচনা করুন'],
  education: ['Highest completed qualification', 'সর্বোচ্চ সম্পন্ন শিক্ষাগত যোগ্যতা'],
  fieldOfStudy: ['Field of study', 'পড়াশোনার বিষয়'],
  skills: ['Skills (comma-separated)', 'দক্ষতাগুলো (কমা দিয়ে আলাদা করুন)'],
  experienceMonths: ['Total work experience (months)', 'মোট কাজের অভিজ্ঞতা (মাস)'],
  experienceRoles: [
    'Previous or current job roles (comma-separated)',
    'আগের বা বর্তমান কাজের পদ (কমা দিয়ে আলাদা করুন)',
  ],
  languages: [
    'Languages you can use (comma-separated)',
    'যেসব ভাষা ব্যবহার করতে পারেন (কমা দিয়ে আলাদা করুন)',
  ],
  desiredRoles: [
    'Desired job roles (comma-separated)',
    'কাঙ্ক্ষিত কাজের পদ (কমা দিয়ে আলাদা করুন)',
  ],
  countries: ['Preferred country', 'পছন্দের দেশ'],
  educationHint: [
    'Select your highest completed qualification and field of study. Choose Other if your answer is not listed. Optional fields may remain blank; no qualification equivalence is inferred.',
    'সর্বোচ্চ সম্পন্ন শিক্ষাগত যোগ্যতা ও পড়াশোনার বিষয় বাছুন। তালিকায় না থাকলে অন্য বিকল্প বাছুন। ঐচ্ছিক ঘর ফাঁকা রাখতে পারেন; যোগ্যতার সমতা ধরে নেওয়া হয় না।',
  ],
  experienceHint: [
    'Select your years of work experience, counting overlapping jobs only once. Choose Other for partial years or exact months. Leave blank if unknown. If you have work experience, describe your job roles.',
    'কাজের অভিজ্ঞতার বছর বাছুন; একই সময়ের একাধিক কাজের সময় একবারই গণনা করুন। আংশিক বছর বা সঠিক মাসের সংখ্যা দিতে অন্য বাছুন। অজানা হলে ফাঁকা রাখুন। অভিজ্ঞতা থাকলে কাজের পদ লিখুন।',
  ],
  preferencesHint: [
    'List the roles you want. Countries are optional if you are undecided. These preferences do not establish permission to work in a country.',
    'যেসব পদে কাজ চান সেগুলো লিখুন। দেশ ঠিক না করলে ফাঁকা রাখতে পারেন। পছন্দ জানানো কোনো দেশে কাজের অনুমতি বোঝায় না।',
  ],
  listHint: [
    'For lists, enter up to 10 items separated by commas, with up to 100 characters per item.',
    'তালিকায় কমা দিয়ে আলাদা করে সর্বোচ্চ ১০টি তথ্য লিখুন, প্রতিটিতে সর্বোচ্চ ১০০ অক্ষর।',
  ],
  required: ['Please provide an answer.', 'একটি উত্তর দিন।'],
  months: [
    'Enter whole months from 0 to 1200, using English or Bengali digits.',
    'ইংরেজি বা বাংলা অঙ্কে ০ থেকে ১২০০ পর্যন্ত পূর্ণ মাস লিখুন।',
  ],
  list: [
    'Enter 1–10 items, each no longer than 100 characters.',
    '১–১০টি তথ্য লিখুন, প্রতিটিতে সর্বোচ্চ ১০০ অক্ষর।',
  ],
  maxlength: ['Keep this answer within 500 characters.', 'উত্তরটি ৫০০ অক্ষরের মধ্যে রাখুন।'],
  optional: ['Optional', 'ঐচ্ছিক'],
  unknown: ['Not provided', 'দেওয়া হয়নি'],
  next: ['Next', 'পরবর্তী'],
  back: ['Back', 'পূর্ববর্তী'],
  edit: ['Edit', 'সম্পাদনা'],
  finish: ['Finish questionnaire', 'প্রশ্নমালা শেষ করুন'],
  step: ['Step', 'ধাপ'],
  of: ['of', '/'],
  restored: [
    'Your unfinished job-seeker draft has been restored.',
    'চাকরিপ্রার্থীর অসমাপ্ত খসড়া ফিরিয়ে আনা হয়েছে।',
  ],
  storage: [
    'Browser storage is unavailable. You can continue, but refreshing may lose your draft.',
    'ব্রাউজারে সংরক্ষণ করা যাচ্ছে না। চালিয়ে যেতে পারেন, তবে রিফ্রেশ করলে খসড়া হারাতে পারে।',
  ],
  validation: ['Correct the highlighted answers to continue.', 'এগোতে চিহ্নিত উত্তরগুলো ঠিক করুন।'],
  reset: ['Clear and start again', 'মুছে আবার শুরু করুন'],
  confirm: ['Clear this job-seeker draft?', 'চাকরিপ্রার্থীর এই খসড়া মুছবেন?'],
  cancel: ['Keep my answers', 'উত্তরগুলো রাখুন'],
  done: ['Questionnaire complete', 'প্রশ্নমালা সম্পন্ন'],
  doneText: [
    'Your profile is ready in this page’s memory. Nothing has been submitted. There are no job listings or eligibility results at this stage. Refreshing or leaving this page clears the completed profile.',
    'এই পৃষ্ঠার মেমোরিতে আপনার প্রোফাইল প্রস্তুত। কিছু পাঠানো হয়নি। এই পর্যায়ে চাকরির তালিকা বা যোগ্যতার ফল নেই। রিফ্রেশ করলে বা পৃষ্ঠা ছাড়লে সম্পন্ন প্রোফাইল মুছে যাবে।',
  ],
  new: ['Start a new questionnaire', 'নতুন প্রশ্নমালা শুরু করুন'],
} satisfies Record<string, readonly [string, string]>;
export type JobTextKey = keyof typeof jobText;
