/** English/Bengali pairs keep presentation copy out of filtering and matching. */
export const searchText = {
  intro: [
    'Explore programs and review their published requirements.',
    'প্রোগ্রাম খুঁজুন এবং প্রকাশিত শর্তগুলো দেখুন।',
  ],
  q: ['Program or institution name', 'প্রোগ্রাম বা প্রতিষ্ঠানের নাম'],
  country: ['Country', 'দেশ'],
  city: ['City', 'শহর'],
  degree: ['Degree level', 'ডিগ্রির স্তর'],
  subject: ['Subject', 'বিষয়'],
  min: ['Minimum annual tuition', 'সর্বনিম্ন বার্ষিক টিউশন'],
  max: ['Maximum annual tuition', 'সর্বোচ্চ বার্ষিক টিউশন'],
  currency: ['Tuition currency', 'টিউশনের মুদ্রা'],
  intake: ['Intake (YYYY-MM)', 'শুরুর মাস (YYYY-MM)'],
  language: ['Language-test requirement', 'ভাষা পরীক্ষার শর্ত'],
  scholarship: ['Scholarship availability', 'বৃত্তির প্রাপ্যতা'],
  institutionType: ['Institution type', 'প্রতিষ্ঠানের ধরন'],
  apply: ['Apply filters', 'ফিল্টার প্রয়োগ করুন'],
  clear: ['Clear filters', 'ফিল্টার মুছুন'],
  all: ['Any', 'সব'],
  unavailable: ['Unavailable option', 'অনুপলব্ধ বিকল্প'],
  filters: ['Search filters', 'খোঁজার ফিল্টার'],
  filterHint: [
    'Tuition filters use annual amounts in one currency; no conversion is made. Intake filters match the start month, not an open application deadline.',
    'টিউশন ফিল্টারে একই মুদ্রায় বার্ষিক অঙ্ক ব্যবহার হয়; রূপান্তর করা হয় না। শুরুর মাস মিললেই আবেদন খোলা আছে বোঝায় না।',
  ],
  invalid: [
    'Check filters: use non-negative tuition amounts, minimum no greater than maximum, a currency for tuition limits, and YYYY-MM for intake. Invalid URL filters must be corrected or cleared.',
    'ফিল্টার ঠিক করুন: টিউশন ঋণাত্মক হবে না, সর্বনিম্ন সর্বোচ্চের বেশি হবে না, টিউশনের মুদ্রা দিন এবং শুরুর মাস YYYY-MM আকারে লিখুন। ভুল URL ফিল্টার সংশোধন বা মুছে ফেলুন।',
  ],
  loading: ['Loading programs…', 'প্রোগ্রাম লোড হচ্ছে…'],
  error: [
    'Program information could not be loaded. Please retry.',
    'প্রোগ্রামের তথ্য লোড হয়নি। আবার চেষ্টা করুন।',
  ],
  retry: ['Retry', 'আবার চেষ্টা করুন'],
  empty: [
    'No published programs are available yet. Development data is not verified study guidance.',
    'এখনো কোনো প্রকাশিত প্রোগ্রাম নেই। উন্নয়নের তথ্য যাচাইকৃত পড়াশোনার নির্দেশনা নয়।',
  ],
  noMatch: [
    'No programs match these filters. Try changing or clearing them.',
    'এই ফিল্টারে কোনো প্রোগ্রাম পাওয়া যায়নি। ফিল্টার বদলান বা মুছুন।',
  ],
  noEligible: [
    'None of the displayed programs has all evaluated requirements met. Review the individual outcomes; unknown information is not a rejection.',
    'দেখানো কোনো প্রোগ্রামের সব যাচাইকৃত শর্ত পূরণ হয়নি। প্রতিটি ফল দেখুন; অজানা তথ্য প্রত্যাখ্যান নয়।',
  ],
  count: ['Programs found', 'পাওয়া প্রোগ্রাম'],
  assessment: ['Start a new questionnaire', 'নতুন প্রশ্নমালা শুরু করুন'],
  noProfile: [
    'Complete a questionnaire to see eligibility outcomes. Completed answers are held only in memory and are lost on refresh; shared links contain filters only.',
    'যোগ্যতার ফল দেখতে প্রশ্নমালা পূরণ করুন। সম্পন্ন উত্তর শুধু মেমোরিতে থাকে; রিফ্রেশ করলে মুছে যায়। শেয়ার করা লিংকে শুধু ফিল্টার থাকে।',
  ],
  profile: [
    'Results use your completed questionnaire. Order: all requirements met, possibly eligible, action required, currently not eligible; then program name. No percentage score is used.',
    'ফলে আপনার সম্পন্ন প্রশ্নমালার উত্তর ব্যবহৃত হচ্ছে। ক্রম: সব শর্ত পূরণ, সম্ভবত যোগ্য, করণীয় আছে, বর্তমানে যোগ্য নয়; তারপর প্রোগ্রামের নাম। শতকরা স্কোর ব্যবহার হয় না।',
  ],
  preferences: [
    'Known destination and degree IDs are carried from the questionnaire link into visible filters. Use filters for city and subject preferences. Self-reported names are not mapped automatically. Scholarship availability does not establish scholarship eligibility.',
    'প্রশ্নমালার জানা দেশ ও ডিগ্রির আইডি লিংকের মাধ্যমে দৃশ্যমান ফিল্টারে আসে। শহর ও বিষয়ের পছন্দের জন্য ফিল্টার ব্যবহার করুন। নিজের লেখা নাম স্বয়ংক্রিয়ভাবে মেলানো হয় না। বৃত্তির প্রাপ্যতা থেকে ব্যক্তিগত যোগ্যতা নিশ্চিত হয় না।',
  ],
  forget: ['Remove completed answers', 'সম্পন্ন উত্তর মুছুন'],
  disclaimer: [
    'This is a preliminary informational assessment based on the information available. It does not guarantee admission, a scholarship, or visa approval.',
    'এটি প্রাপ্ত তথ্যের ভিত্তিতে প্রাথমিক তথ্যভিত্তিক মূল্যায়ন। এটি ভর্তি, বৃত্তি বা ভিসা অনুমোদনের নিশ্চয়তা দেয় না।',
  ],
  eligibleBasedOnAvailableInformation: [
    'Eligible based on available information',
    'প্রাপ্ত তথ্য অনুযায়ী যোগ্য',
  ],
  possiblyEligible: ['Possibly eligible', 'সম্ভবত যোগ্য'],
  actionRequired: ['Action required', 'করণীয় আছে'],
  currentlyNotEligible: ['Currently not eligible', 'বর্তমানে যোগ্য নয়'],
  met: ['Met', 'পূরণ হয়েছে'],
  notMet: ['Not met', 'পূরণ হয়নি'],
  unknown: ['Unknown', 'অজানা'],
  satisfied: ['The supplied answer meets this requirement.', 'দেওয়া উত্তর এই শর্ত পূরণ করে।'],
  notSatisfied: [
    'The supplied answer does not meet this requirement.',
    'দেওয়া উত্তর এই শর্ত পূরণ করে না।',
  ],
  programInformationMissing: ['Program information is incomplete.', 'প্রোগ্রামের তথ্য অসম্পূর্ণ।'],
  studentInformationMissing: [
    'More information is needed from your profile.',
    'আপনার প্রোফাইলের আরও তথ্য প্রয়োজন।',
  ],
  notComparable: [
    'Values or identities cannot be compared safely; no equivalence or conversion was assumed.',
    'অঙ্ক বা পরিচয় নির্ভরযোগ্যভাবে তুলনা করা যায়নি; সমতা বা রূপান্তর ধরে নেওয়া হয়নি।',
  ],
  noRestriction: [
    'No language-test requirement is listed in the known requirement set.',
    'জানা শর্তের তালিকায় ভাষা পরীক্ষার শর্ত নেই।',
  ],
  deadlinePassed: ['The application deadline has passed.', 'আবেদনের শেষ সময় পেরিয়ে গেছে।'],
  education: ['Education level', 'শিক্ষাস্তর'],
  academicBackground: ['Academic background', 'শিক্ষাগত বিষয়'],
  gpa: ['Academic result', 'শিক্ষাগত ফলাফল'],
  tuitionBudget: ['Tuition budget', 'টিউশন বাজেট'],
  studyGap: ['Study gap', 'পড়াশোনায় বিরতি'],
  workExperience: ['Work experience', 'কাজের অভিজ্ঞতা'],
  mandatory: ['Mandatory', 'বাধ্যতামূলক'],
  optional: ['Not marked mandatory', 'বাধ্যতামূলক হিসেবে চিহ্নিত নয়'],
  mandatoryUnknown: ['Mandatory status unknown', 'বাধ্যতামূলক কি না অজানা'],
  failed: ['Mandatory requirements not met', 'বাধ্যতামূলক শর্ত পূরণ হয়নি'],
  verified: ['Verified', 'যাচাইকৃত'],
  unverified: ['Unverified', 'যাচাই হয়নি'],
  needsReview: ['Needs review', 'পর্যালোচনা প্রয়োজন'],
  lastChecked: ['Last checked', 'সর্বশেষ পরীক্ষা'],
  evaluated: ['Evaluated at (UTC)', 'মূল্যায়নের সময় (UTC)'],
  sources: ['Sources', 'উৎস'],
  noSources: ['No source supplied', 'উৎস দেওয়া হয়নি'],
  tuition: ['Tuition', 'টিউশন'],
  annual: ['per year', 'প্রতি বছর'],
  semester: ['per semester', 'প্রতি সেমিস্টার'],
  total: ['total', 'মোট'],
  oneTime: ['one-time', 'একবার'],
  yes: ['Available', 'আছে'],
  no: ['Not available', 'নেই'],
  none: ['No test requirement', 'পরীক্ষার শর্ত নেই'],
  required: ['Test requirement listed', 'পরীক্ষার শর্ত আছে'],
  public: ['Public', 'সরকারি'],
  private: ['Private', 'বেসরকারি'],
  other: ['Other', 'অন্যান্য'],
  details: ['Requirements and outcomes', 'শর্ত ও ফলাফল'],
  minimum: ['Minimum', 'সর্বনিম্ন'],
  maximum: ['Maximum', 'সর্বোচ্চ'],
  years: ['years', 'বছর'],
  months: ['months', 'মাস'],
  overall: ['Overall', 'সামগ্রিক'],
  reading: ['Reading', 'পড়া'],
  writing: ['Writing', 'লেখা'],
  listening: ['Listening', 'শোনা'],
  speaking: ['Speaking', 'বলা'],
  starts: ['Starts', 'শুরু'],
  deadline: ['Deadline', 'শেষ সময়'],
  noAccepted: ['No accepted entries listed', 'গ্রহণযোগ্য কোনো মান তালিকাভুক্ত নেই'],
} satisfies Record<string, readonly [string, string]>;
export type SearchTextKey = keyof typeof searchText;
